"""initial market intelligence schema

Revision ID: 55e701907026
Revises: 
Create Date: 2026-03-25 17:03:35.724487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '55e701907026'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_payload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_term', sa.Text(), nullable=False),
    sa.Column('normalized_term', sa.Text(), nullable=False),
    sa.Column('candidate_type', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('raw_payload_hash', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('competition_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ops_risk_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('score_version', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_score')
    op.drop_table('trend_snapshot')
    op.drop_table('candidate')
    op.drop_table('api_payload')
    # ### end Alembic commands ###
