"""add candidate qualification fields

Revision ID: d4fb6f3df9fd
Revises: 30ed7eb66173
Create Date: 2026-03-25 19:55:27.116063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd4fb6f3df9fd'
down_revision: Union[str, Sequence[str], None] = '30ed7eb66173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "candidate",
        sa.Column(
            "qualification_status",
            sa.Text(),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column(
        "candidate",
        sa.Column(
            "qualification_reason",
            sa.Text(),
            nullable=True,
        ),
    )
    op.add_column(
        "candidate",
        sa.Column(
            "last_qualified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.alter_column(
        "candidate",
        "qualification_status",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'last_qualified_at')
    op.drop_column('candidate', 'qualification_reason')
    op.drop_column('candidate', 'qualification_status')
    # ### end Alembic commands ###
